FROM python:3.11-slim

# Define o diretório de trabalho
WORKDIR /app

# Copie o arquivo requirements.txt para o contêiner
COPY requirements.txt .

# Instala as dependências
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Copia os arquivos do projeto
COPY . .

# Define as variáveis de ambiente
ENV PORT=5000
ENV FLASK_APP=run.py
ENV FLASK_ENV=production
ENV SMTP_SERVER="smtp.gmail.com"
ENV SMTP_PORT=465
ENV RECAPTCHA_URL="https://www.google.com/recaptcha/api/siteverify"
ENV ORIGINS="http://localhost:5000"
ENV MAIL_AUTH_USER="joaorovera73@gmail.com"
ENV MAIL_AUTH_PASS="axju idyp dexx swhu"
ENV TEXT_MAIL_TITLE="Formulário de Contato"
ENV DESTINY="{email}"
ENV TEXT_MAIL_BODY="E-mail de: {email} Assunto: {comment}"
ENV TEXT_MAIL_HTML="Assunto: {comment}"

# Exponha a porta que o Flask irá rodar
EXPOSE $PORT

# Comando para iniciar a aplicação Flask
CMD ["flask", "run", "--host=0.0.0.0"]
