FROM python:3.11-slim

# Define o diretório de trabalho
WORKDIR /app

# Copie o arquivo requirements.txt para o contêiner
COPY requirements.txt .

# Instala as dependências
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Copia os arquivos do projeto
COPY . .

# Define as variáveis de ambiente
ENV PORT=5000
ENV FLASK_APP=run.py
ENV FLASK_ENV=production
ENV SMTP_SERVER="smtp.gmail.com"
ENV SMTP_PORT=587
ENV ORIGINS="http://localhost:5000"

# Exponha a porta que o Flask irá rodar
EXPOSE $PORT

# Comando para iniciar a aplicação Flask
CMD ["flask", "run", "--host=0.0.0.0"]
